### ISSUE TITLE
能支持AndroidTV吗？就是电视

### ISSUE THREAD

**Issue by androidcn** [duzhaokun123/BilibiliHD2#1]
能支持AndroidTV吗？就是电视
电视遥控器

**Comment by duzhaokun123** [comment]
键盘体验很差

**Comment by androidcn** [comment]
刚测试了一下AndroidTV能打开App，能显示主页和卡卡，无法播放视频，登录要抓包，

**Comment by duzhaokun123** [comment]
有 log 没

**Comment by androidcn** [comment]
在哪看log。。。

**Comment by duzhaokun123** [comment]
能 adb 不
给你发个 debug 包

**Comment by duzhaokun123** [comment]
不能的话 我加个导出日志功能

**Comment by androidcn** [comment]
导入导出都受限
AndroidTV无法弹出文件框的

abd我可以尝试用一下

wifi adb

**Comment by androidcn** [comment]
刚才使用飞鼠，点击 视频按钮，可以进去，看视频了，能正常播放，

可以解决一下，所有按钮支持一下遥控点击和上下左右移动控制吗？
目前只能使用飞鼠的模拟点击。

选择分辨率的选项也不支持遥控上下移动

**Comment by androidcn** [comment]
https://developer.aliyun.com/article/676806

https://zhuanlan.zhihu.com/p/34194412

可能要 加入 一些 遥控器监听的代码了
我找了一下 文章 不知道对你有没有用。

**Comment by duzhaokun123** [comment]
原来是点不到无法播放
最近主要是把 api 换成 web 因为验证好过还可以扫码登录
另外现在的 ui 框架也可能换掉
遥控/键盘 支持会排的非常后

**Comment by duzhaokun123** [comment]
登录问题如果有 root 可以解决

**Comment by androidcn** [comment]
哈，没有root，Sony的AndroidTV

**Comment by duzhaokun123** [comment]
那只能等出扫码登录了
